version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.STAFFBOT_NPM_READ}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    registries:
      - npm-github
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
