name: 'AutoDev action'
description: 'Tries to merge all Pull Requests with a specific label to a certain branch.'
branding:
  icon: 'git-merge'
  color: 'blue'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  token:
    required: true
    description: GitHub token of the user that fetches the pull requests
  base:
    required: false
    default: 'main'
    description: 'This is the base branch. The merge history originates from this branch.'
  label:
    required: false
    default: 'dev'
    description: 'The label where the action will be triggered.'
  branch:
    required: false
    default: 'dev'
    description: 'The branch the action will merge the Pull Requests to.'
  comments:
    required: false
    default: 'false'
    description: 'If true, the action creates a comment on each PR to inform about the status of the dev branch'
  success_comment:
    required: false
    description: 'Comment string that will be shown in the Pull request on success.'
    default: ''
  failure_comment:
    required: false
    description: 'Comment string that will be shown in the Pull request on failure.'
    default: ''
  labels:
    required: false
    default: 'false'
    description: 'If true, the action uses labels on each PR to inform about the status of the dev branch.'
  success_label:
    required: false
    description: 'Label string that will be add on the Pull request on success.'
    default: 'successful'
  failure_label:
    required: false
    description: 'Label string that will be add on the Pull request on failure.'
    default: 'failed'
  user:
    required: false
    default: 'AutoDev Action'
    description: 'Name of the user which does the git commit.'
  email:
    required: false
    default: 'staffbot@staffbase.com'
    description: 'E-Mail of the user which does the git commit.'
