name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'releases/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4

      - name: Install Dependencies
        run: mise run install

      - name: Build Action
        run: mise run all

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Execute Action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ secrets.DEV_PUSH_USER }}
          labels: true
          comments: true

  dependabot:
    needs: [build, test]
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@7433384f8737623f2c8eb247427830629ce66d97 # v14.1.0
    with:
      force: true
    secrets:
      client-id: ${{ vars.STAFFBASE_ACTIONS_CLIENT_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
