name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'releases/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4

      - name: Install Dependencies
        run: mise run install

      - name: Build Action
        run: mise run all

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Execute Action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ secrets.DEV_PUSH_USER }}
          labels: true
          comments: true

  dependabot:
    needs: [build, test]
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@a38088448bfd106dbabe9f3b88f8cc8c88aaec83 # v15.1.1
    with:
      force: true
    secrets:
      client_id: ${{ vars.STAFFBASE_ACTIONS_CLIENT_ID }}
      private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
