name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    uses: Staffbase/gha-workflows/.github/workflows/template_release_drafter.yml@7433384f8737623f2c8eb247427830629ce66d97 # v14.1.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
